import { createServer } from "node:http";
import { readFile, writeFile } from "node:fs/promises";
import { extname, join, normalize, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL(".", import.meta.url)).replace(/[\\/]+$/, "");
const PORT = Number(process.env.PORT) || 8080;

const REQUIRED_ENV = [
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID",
];

const missing = REQUIRED_ENV.filter(k => !process.env[k]);
if (missing.length) {
  console.error(
    `Missing env vars: ${missing.join(", ")}\n` +
    `Copy .env.example to .env and fill in values from Firebase console.`
  );
  process.exit(1);
}

const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID,
  ...(process.env.FIREBASE_MEASUREMENT_ID
    ? { measurementId: process.env.FIREBASE_MEASUREMENT_ID }
    : {}),
};

const configModule =
  `// Generated by server.js from .env — do not commit, do not edit by hand.\n` +
  `export const firebaseConfig = ${JSON.stringify(firebaseConfig, null, 2)};\n`;

await writeFile(join(ROOT, "js", "firebase-config.js"), configModule, "utf8");
console.log("Wrote js/firebase-config.js from .env");

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js":   "application/javascript; charset=utf-8",
  ".mjs":  "application/javascript; charset=utf-8",
  ".css":  "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg":  "image/svg+xml",
  ".png":  "image/png",
  ".jpg":  "image/jpeg",
  ".ico":  "image/x-icon",
  ".woff2":"font/woff2",
};

createServer(async (req, res) => {
  const url = decodeURIComponent(req.url.split("?")[0]);
  const rel = normalize(url === "/" ? "/index.html" : url).replace(/^([/\\])+/, "");
  const abs = join(ROOT, rel);

  if (!abs.startsWith(ROOT + sep) && abs !== ROOT) {
    res.writeHead(403).end("forbidden");
    return;
  }

  try {
    const body = await readFile(abs);
    res.writeHead(200, {
      "Content-Type": MIME[extname(abs).toLowerCase()] || "application/octet-stream",
      "Cache-Control": "no-cache",
    });
    res.end(body);
  } catch {
    res.writeHead(404, { "Content-Type": "text/plain" }).end("not found");
  }
}).listen(PORT, () => {
  console.log(`Zakinspired dev server → http://localhost:${PORT}`);
});
